worker_processes  1;

events { worker_connections 1024; }

http {
    upstream backend {
        server app1:80;
        server app2:80;
    }

    server {
        listen 80;
        server_tokens off;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        error_page 502 503 504 /custom_50x.html;
        location = /custom_50x.html {
            root /usr/share/nginx/html;
            internal;
        }
    }
}